import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  Action,
  Box,
  RadioGroup,
  Radio,
  Stack,
  Heading,
  Checkbox,
  // CheckboxGroup,
    Tag,
  Text,
} from "@tuftandneedle/design-system";
import { UIProvider } from "@tuftandneedle/design-system/config/UIProvider";
import { tuftandneedle as theme } from "@tuftandneedle/design-system/themes/tuftandneedle";

const Home: NextPage = () => {

  const look = `var(--chakra-colors-palette-mediumGray)`;
  const size = 'sm';
  const complexDetails = ({ size }) => (
    <Box>
      <Text color={look} fontSize={size}>A complex detail</Text>
      <Action color={look}>Additional input</Action>
    </Box>
  );
  const noop = () => null;

  const items = [
    {
      label: 'Radio Option 1',
      details: complexDetails,
    },
    {
      label: 'Radio Option 2',
      details: 'Details for Radio Option 2',
    },
    {
      label: 'Radio Option 3',
      details: <Text>Details for Radio Option 3</Text>,
    },
  ];

  return (
    <UIProvider theme={theme}
    resetCSS={false}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Heading>
          HEADING
        </Heading>


        <Action
          colorScheme="night"
          customWidth="default"
          onClick={() => {}}
          type="primary"
        >
          Button
        </Action>
        <Tag variant={'new'} size={'sm'}>NEW</Tag>
        <br />
        <br />

        {/* <CheckboxGroup onChange={(value) => console.log(value)}>
          <Stack>
            <Checkbox value="one">One</Checkbox>
            <Checkbox value="two">Two</Checkbox>
            <Checkbox value="three">Three</Checkbox>
          </Stack>
        </CheckboxGroup> */}

    {/*<RadioGroupDetailed onChange={noop} items={items} isVisuallyHidden={true}/>*/}
     
      </div>
    </UIProvider>
  )
}

export default Home
